"""Report Generator Module"""

import numpy as np
from pathlib import Path
from typing import Dict, Optional, Any
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate analysis reports in various formats"""
    
    def __init__(self, title: str = "TRN Analysis Report"):
        """
        Initialize report generator
        
        Args:
            title: Report title
        """
        self.title = title
        self.content = {}
        self.timestamp = datetime.now()
    
    def add_section(self, section_name: str, content: str) -> None:
        """
        Add section to report
        
        Args:
            section_name: Section title
            content: Section content
        """
        self.content[section_name] = content
        logger.info(f"Added section: {section_name}")
    
    def add_analysis_results(self, results: Dict[str, Any]) -> None:
        """
        Add analysis results to report
        
        Args:
            results: Dictionary of analysis results
        """
        content = "<h3>Analysis Results</h3>\n<table border='1' cellpadding='5'>\n"
        for key, value in results.items():
            if isinstance(value, float):
                content += f"<tr><td><b>{key}</b></td><td>{value:.2f}</td></tr>\n"
            else:
                content += f"<tr><td><b>{key}</b></td><td>{value}</td></tr>\n"
        content += "</table>\n"
        self.add_section("Analysis Results", content)
    
    def add_file_information(self, file_path: str, sample_rate: float,
                            duration: float, file_size_mb: float) -> None:
        """
        Add file information section
        
        Args:
            file_path: Path to audio file
            sample_rate: Sampling frequency
            duration: Duration in seconds
            file_size_mb: File size in MB
        """
        content = f"""
        <h3>File Information</h3>
        <table border='1' cellpadding='5'>
        <tr><td><b>File:</b></td><td>{Path(file_path).name}</td></tr>
        <tr><td><b>Sample Rate:</b></td><td>{sample_rate:,.0f} Hz</td></tr>
        <tr><td><b>Duration:</b></td><td>{duration:.2f} seconds</td></tr>
        <tr><td><b>File Size:</b></td><td>{file_size_mb:.2f} MB</td></tr>
        </table>
        """
        self.add_section("File Information", content)
    
    def add_parameters(self, parameters: Dict[str, Any]) -> None:
        """
        Add analysis parameters section
        
        Args:
            parameters: Dictionary of parameters used
        """
        content = "<h3>Analysis Parameters</h3>\n<table border='1' cellpadding='5'>\n"
        for key, value in parameters.items():
            content += f"<tr><td><b>{key}</b></td><td>{value}</td></tr>\n"
        content += "</table>\n"
        self.add_section("Analysis Parameters", content)
    
    def generate_html(self) -> str:
        """
        Generate HTML report
        
        Returns:
            HTML content as string
        """
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{self.title}</title>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    margin: 20px;
                    background-color: #f5f5f5;
                }}
                h1 {{
                    color: #333;
                    border-bottom: 2px solid #007bff;
                    padding-bottom: 10px;
                }}
                h3 {{
                    color: #555;
                    margin-top: 20px;
                }}
                table {{
                    background-color: white;
                    border-collapse: collapse;
                }}
                td {{
                    padding: 8px;
                }}
                .footer {{
                    margin-top: 30px;
                    font-size: 12px;
                    color: #999;
                    border-top: 1px solid #ddd;
                    padding-top: 10px;
                }}
            </style>
        </head>
        <body>
            <h1>{self.title}</h1>
            <p><b>Generated:</b> {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</p>
        """
        
        # Add sections
        for section_name, section_content in self.content.items():
            html += f"\n{section_content}\n"
        
        # Add footer
        html += f"""
            <div class="footer">
                <p>This report was generated by TRN Analysis Software v0.1.0</p>
                <p>For more information, visit: https://github.com/onur456akin-cmyk/TRN-Analysis-Software_v2</p>
            </div>
        </body>
        </html>
        """
        
        logger.info("HTML report generated")
        return html
    
    def save_html(self, file_path: Path) -> None:
        """
        Save report as HTML file
        
        Args:
            file_path: Output file path
        """
        html_content = self.generate_html()
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        logger.info(f"HTML report saved to {file_path}")
    
    def save_txt(self, file_path: Path) -> None:
        """
        Save report as text file
        
        Args:
            file_path: Output file path
        """
        txt_content = f"{self.title}\n"
        txt_content += f"Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}\n"
        txt_content += "=" * 80 + "\n\n"
        
        for section_name, section_content in self.content.items():
            txt_content += f"{section_name}\n"
            txt_content += "-" * len(section_name) + "\n"
            # Remove HTML tags for text version
            import re
            clean_content = re.sub('<[^<]+?>', '', section_content)
            txt_content += clean_content + "\n\n"
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(txt_content)
        logger.info(f"Text report saved to {file_path}")


if __name__ == "__main__":
    print("Report Generator module loaded")
